# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(175, 260)
        MainWindow.setMinimumSize(QtCore.QSize(175, 260))
        MainWindow.setMaximumSize(QtCore.QSize(175, 260))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Install = QtWidgets.QLabel(self.centralwidget)
        self.Install.setGeometry(QtCore.QRect(0, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Install.setFont(font)
        self.Install.setObjectName("Install")
        self.InstallLine = QtWidgets.QLineEdit(self.centralwidget)
        self.InstallLine.setGeometry(QtCore.QRect(0, 30, 171, 20))
        self.InstallLine.setObjectName("InstallLine")
        self.Update = QtWidgets.QLabel(self.centralwidget)
        self.Update.setGeometry(QtCore.QRect(0, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Update.setFont(font)
        self.Update.setObjectName("Update")
        self.UpdateLine = QtWidgets.QLineEdit(self.centralwidget)
        self.UpdateLine.setGeometry(QtCore.QRect(0, 80, 171, 20))
        self.UpdateLine.setObjectName("UpdateLine")
        self.Delete = QtWidgets.QLabel(self.centralwidget)
        self.Delete.setGeometry(QtCore.QRect(0, 110, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Delete.setFont(font)
        self.Delete.setObjectName("Delete")
        self.DeleteLine = QtWidgets.QLineEdit(self.centralwidget)
        self.DeleteLine.setGeometry(QtCore.QRect(0, 130, 171, 20))
        self.DeleteLine.setObjectName("DeleteLine")
        self.Name = QtWidgets.QLabel(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(60, 230, 61, 21))
        self.Name.setObjectName("Name")
        self.Run = QtWidgets.QPushButton(self.centralwidget)
        self.Run.setGeometry(QtCore.QRect(0, 160, 171, 23))
        self.Run.setObjectName("Run")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 220, 191, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Info = QtWidgets.QPushButton(self.centralwidget)
        self.Info.setGeometry(QtCore.QRect(0, 190, 171, 23))
        self.Info.setObjectName("Info")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PM"))
        self.Install.setText(_translate("MainWindow", "Install Module"))
        self.Update.setText(_translate("MainWindow", "Update Module"))
        self.Delete.setText(_translate("MainWindow", "Delete Module"))
        self.Name.setText(_translate("MainWindow", "Pip Manager"))
        self.Run.setText(_translate("MainWindow", "Run"))
        self.Info.setText(_translate("MainWindow", "Info"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
